# Generated by Django 5.1 on 2024-08-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_populate_day_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='abbr',
            field=models.CharField(max_length=4),
        ),
    ]
